name: Build and Deploy Docs

on:
  push:
    branches:
      - '**'  # Change this if your default branch is different
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install sphinx myst-parser sphinx-rtd-theme

      - name: Copy README.md Files to Docs
        run: |
          mkdir -p docs/source
          find . -name "README.md" -exec cp --parents {} docs/source/ \;
          mv docs/source/README.md docs/source/index.md  # Root README becomes index

      - name: Create Sphinx Config
        run: |
          cat << EOF > docs/source/conf.py
          import os
          project = 'Wall-E Docs'
          html_theme = 'sphinx_rtd_theme'
          extensions = ['myst_parser']
          source_suffix = ['.md']
          html_static_path = ['_static']
          templates_path = ['_templates']
          EOF

      - name: Build Sphinx Documentation
        run: |
          sphinx-build -M html docs/source docs/build
          touch docs/build/html/.nojekyll  # Add .nojekyll after building

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          keep_files: true  # Keeps CNAME if it exists
          cname: 'walle.sravjti.in'  # Change if using a different domain
